parameters:

services:
    ddr.twig.bootstrap.pagination_extension:
        class: Dontdrinkandroot\Symfony\ExtensionBundle\Twig\BootstrapPaginationExtension
        arguments: ["@router"]
        tags:
            - { name: twig.extension }
